apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-app-staging
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/apeksha-ui98/k8s-platform-engineering.git
    targetRevision: main
    path: helm/platform-app

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
